/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diego
 */
public class VAutentificacion extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    aplicacion.InterfazServidor server;

    /**
     * Creates new form VAutentificacion
     */
    public VAutentificacion(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        initComponents();
        this.fa = fa;
        Merror.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BNombreusuario = new javax.swing.JTextField();
        Thostn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TPortN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Bentrar = new javax.swing.JButton();
        Bregistro = new javax.swing.JButton();
        Merror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Thostn.setText("localhost");

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Contraseña: ");

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Bienvenido a Hack Chat");

        jLabel4.setText("Host name:");

        TPortN.setText("1099");

        jLabel5.setText("Port number:");

        Bentrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Bentrar.setText("Entrar");
        Bentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BentrarActionPerformed(evt);
            }
        });

        Bregistro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Bregistro.setText("Registro");
        Bregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregistroActionPerformed(evt);
            }
        });

        Merror.setForeground(new java.awt.Color(255, 0, 0));
        Merror.setText("Completa todos los campos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel3)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Bregistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bentrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Thostn)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(TPortN, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BNombreusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Merror)
                                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Thostn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TPortN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BNombreusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(Merror)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bentrar)
                    .addComponent(Bregistro))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BentrarActionPerformed
        // TODO add your handling code here:
        if (!this.BNombreusuario.getText().isEmpty() && !this.jPassword.getText().isEmpty() && !this.TPortN.getText().isEmpty() && !this.Thostn.getText().isEmpty()) {
            System.out.println(this.BNombreusuario.getText());
            System.out.println(this.jPassword.getText());
            try {
                //Inicializamos el resgistro RMI
                String registryURL = "rmi://" + this.Thostn.getText() + ":" + this.TPortN.getText() + "/callback";
                System.out.println(registryURL);
                aplicacion.InterfazServidor h = (aplicacion.InterfazServidor) Naming.lookup(registryURL);
                this.server = h;
                this.fa.setServer(server);
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(VAutentificacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if (this.server.LogIn(this.fa.getUser(), BNombreusuario.getText(), this.jPassword.getText())) {
                    this.dispose();
                    this.fa.mostrarVprincipal(this.BNombreusuario.getText());
                    //Notifica Amigos conexion
                    System.out.println("Se conecto correctamente");
                }else{
                    Merror.setText("Usuario ya conectado");
                    Merror.setVisible(true);
                }
            } catch (RemoteException ex) {
                Logger.getLogger(VAutentificacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Merror.setText("Completa todos los campos");
            Merror.setVisible(true);
        }
    }//GEN-LAST:event_BentrarActionPerformed

    private void BregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregistroActionPerformed
        // TODO add your handling code here:
        if (!this.TPortN.getText().isEmpty() && !this.Thostn.getText().isEmpty()) {
            try {
                //Inicializamos el resgistro RMI
                String registryURL = "rmi://" + this.Thostn.getText() + ":" + this.TPortN.getText() + "/callback";
                System.out.println(registryURL);
                aplicacion.InterfazServidor h = (aplicacion.InterfazServidor) Naming.lookup(registryURL);
                this.server = h;
                this.dispose();
                this.fa.mostrarRegistro(this.server);
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(VAutentificacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            Merror.setText("Completa todos los campos");
            Merror.setVisible(true);
        }
    }//GEN-LAST:event_BregistroActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BNombreusuario;
    private javax.swing.JButton Bentrar;
    private javax.swing.JButton Bregistro;
    private javax.swing.JLabel Merror;
    private javax.swing.JTextField TPortN;
    private javax.swing.JTextField Thostn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPassword;
    // End of variables declaration//GEN-END:variables
}
