/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diego
 */
public class VPrincipal extends javax.swing.JFrame {

    
    private aplicacion.FachadaAplicacion fa;
    private String id;
    /**
     * Creates new form VPrincipal
     */
    public VPrincipal(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa,String id) {
        initComponents();
        this.TNombre.setText("Hola: " + id);
        BChat.setEnabled(false);
        this.fa = fa;
        this.id = id;
    }
    
    public void actualizar_ventanaConectados(ArrayList<aplicacion.Usuario> amigos) {
        ModeloTablaConectados m = (ModeloTablaConectados) tablaconectados.getModel();
        ArrayList<String> aux = new ArrayList();
        
        for(aplicacion.Usuario user : amigos){
            aux.add(user.getId());
        }
        m.setFilas(aux);
    }
    
    public void actualizar_ventanaDesconectados(ArrayList<String> desconectados) {
        ModeloTablaDesconectados m = (ModeloTablaDesconectados) tabladesconectados.getModel();
        m.setFilas(desconectados);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconectados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladesconectados = new javax.swing.JTable();
        TNombre = new javax.swing.JLabel();
        BEditarperf = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        BChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaconectados.setModel(new ModeloTablaConectados());
        tablaconectados.setName("Amigos conectados"); // NOI18N
        tablaconectados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaconectadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaconectados);

        tabladesconectados.setModel(new ModeloTablaDesconectados());
        tabladesconectados.setName("Amigos desconectados"); // NOI18N
        jScrollPane2.setViewportView(tabladesconectados);

        TNombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TNombre.setText("Hola:");

        BEditarperf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BEditarperf.setText("Editar perfil");
        BEditarperf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditarperfActionPerformed(evt);
            }
        });

        BSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        BChat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BChat.setText("Chatear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 634, Short.MAX_VALUE)
                        .addComponent(TNombre)
                        .addGap(160, 160, 160)
                        .addComponent(BEditarperf))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BChat)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BSalir)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TNombre)
                    .addComponent(BEditarperf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BChat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BSalir)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        try {
            // TODO add your handling code here:
            this.fa.getServer().LogOut(this.fa.getUser(), id);
        } catch (RemoteException ex) {
            Logger.getLogger(VPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_BSalirActionPerformed

    private void BEditarperfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditarperfActionPerformed
        // TODO add your handling code here:
        this.fa.mostrarVEditar(id);
    }//GEN-LAST:event_BEditarperfActionPerformed

    private void tablaconectadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaconectadosMouseClicked
        // TODO add your handling code here:
        BChat.setEnabled(true);
    }//GEN-LAST:event_tablaconectadosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BChat;
    private javax.swing.JButton BEditarperf;
    private javax.swing.JButton BSalir;
    private javax.swing.JLabel TNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaconectados;
    private javax.swing.JTable tabladesconectados;
    // End of variables declaration//GEN-END:variables
}
